version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Expose for local development/debugging, remove in production if not needed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env # This will load environment variables from .env file in the infrastructure folder
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      # Other environment variables like GOOGLE_API_KEY, TWITTER_API_KEY, etc. should be in .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      VITE_API_BASE_URL: http://localhost:80 # Frontend will access Nginx on port 80
    ports:
      - "3000:80" # Map host port 3000 to container's Nginx port 80
    depends_on:
      - backend

volumes:
  db_data:
